language: node_js
node_js:
  - "10.10.0"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - cd web
  - npm install -g @angular/cli
  - npm install


script:
  - ng lint
  - ng build --prod