language: node_js
node_js:
  - "10.10.0"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - cd web
  - npm install -g @angular/cli
  - npm install


script:
  - ng lint
  - npm run test-headless
  # - ng e2e
  - ng build --prod --base-href https://ibrahim-sobhy.github.io/hadeeth

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: web/dist/web
  on:
    branch: master

