
service: api 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    HADEETH_TABLE: ${self:custom.table.name}
    URL: { "Fn::Join" : ["", [" https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}" ] ]  }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-mocha-plugin

functions:
  hadeeth:
    handler: functions/handler.handler
    events:
    - http:
        path: /api/hadeeth/{id}
        method: get
        request:
          parameters:
            paths:
              id: true

resources:
  - ${file(resources/dynamodb-table.yml)}
    
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  table:
    name: Hadeeth
    readThroughput: 3
    writeThroughput: 3
